version: "3.9"

networks:
  internal:
    driver: bridge

volumes:
  mongo_data:

services:
    mongo:
      image: mongo:latest
      restart: always 
      ports:
        - "27017:27017"
    
    students-microservice: 
      build:
          context: microservice1
          dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on: 
        - mongo
    
    courses-microservice: 
      build:
          context: microservice2
          dockerfile: Dockerfile
      ports:
        - "8081:8081"
      depends_on: 
        - mongo